class ApiConstants {
  static String accessToken =
      "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhNzczYWE5NDc4YzYyMmY1ZGRjZjZjN2ZhZTViYzI3MSIsInN1YiI6IjY1MzBlZjcxMzBmNzljMDBlMWMwMWY4MCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.s_qIrTkihkU15Yg_Xp2wns45zFhTRmetTvvearo3ulc";
}
